name: Discord Changelog

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get commit info
        run: |
          echo "DATE=$(date '+%d/%m/%Y')" >> $GITHUB_ENV
          echo "AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV

      - name: Get commits
        run: |
          ADDED=$(git log -10 --pretty=format:"%s" | grep -i "^feat" | sed 's/^feat: /**•** /')
          CHANGED=$(git log -10 --pretty=format:"%s" | grep -i "^change" | sed 's/^change: /**•** /')
          FIXED=$(git log -10 --pretty=format:"%s" | grep -i "^fix" | sed 's/^fix: /**•** /')

          echo "ADDED<<EOF" >> $GITHUB_ENV
          echo "$ADDED" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "CHANGED<<EOF" >> $GITHUB_ENV
          echo "$CHANGED" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "FIXED<<EOF" >> $GITHUB_ENV
          echo "$FIXED" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send Embed
        run: |
          curl -H "Content-Type: application/json" \
          -d "{
            \"embeds\": [{
              \"title\": \"📢 CHANGELOG - ATUALIZAÇÃO DO SERVIDOR | ${DATE}\",
              \"description\": \"**👤 Autor:** ${AUTHOR}\n\n________________\n\n** Added**\n${ADDED:-• Nenhuma alteração}\n\n** Changed**\n${CHANGED:-• Nenhuma alteração}\n\n** Fixed**\n${FIXED:-• Nenhuma alteração}\n\n________________\",
              \"color\": 16766720,
              \"footer\": {
                \"text\": \"Atualização enviada automaticamente pelo GitHub\"
              }
            }]
          }" \
          ${{ secrets.ULTRA_BOT }}